name: Gradle CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run Tests
        run: ./gradlew test --no-daemon

      - name: Upload Test Reports (JUnit XML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-xml-reports
          path: build/test-results/test

      - name: Upload Test Reports (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-html-reports
          path: build/reports/tests/test

      - name: Publish Test Summary
        if: always()
        uses: test-summary/action@v2
        with:
          paths: build/test-results/test/*.xml
